name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flake-check:
    name: "Flake Check"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            system-features = nixos-test benchmark big-parallel kvm

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      # Run full flake check on both platforms
      # Both Linux and macOS can run NixOS VM tests via QEMU
      - name: Run flake check
        run: nix flake check -L --show-trace

  # Run NixOS integration tests in parallel on both Linux and macOS
  nixos-integration-tests:
    name: "NixOS Integration Test - ${{ matrix.test }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        test: [simple, cli, performance]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            system-features = nixos-test benchmark big-parallel kvm

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run NixOS Integration Test - ${{ matrix.test }}
        run: |
          # Determine the system based on OS
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            SYSTEM="x86_64-linux"
          else
            SYSTEM="aarch64-darwin"
          fi

          echo "Running test on system: $SYSTEM"
          nix build .#checks.$SYSTEM.${{ matrix.test }} -L --show-trace

  # Additional parallel checks for better visibility
  parallel-checks:
    name: "${{ matrix.check }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        check: [sshbind, sshbind-clippy, sshbind-fmt, sshbind-audit, sshbind-deny, sshbind-doc, pre-commit-check]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run Check - ${{ matrix.check }}
        run: |
          # Determine the system based on OS
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            SYSTEM="x86_64-linux"
          else
            SYSTEM="aarch64-darwin"
          fi

          echo "Running check on system: $SYSTEM"
          nix build .#checks.$SYSTEM.${{ matrix.check }} -L --show-trace
